development:
  adapter: postgresql
  database: jep_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: jep_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: jep_production
  pool: 5
  timeout: 5000
